// styles.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  appContainer: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: 6,
    paddingBottom: 16,
  },
  // Add a default text style that can be inherited
  defaultText: {
    fontSize: 16, // Base font size
  },

  innerContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 32,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  menuButton: { padding: 8, marginRight: 12 },
  hamburger: { width: 22, justifyContent: 'center' },
  hamburgerLine: { height: 2, marginVertical: 2, backgroundColor: '#222' },
  searchButton: { padding: 8 },
  searchIcon: { fontSize: 18 },

  titleSection: { marginBottom: 20 },
  mainTitle: { fontSize: 28, fontWeight: '700' },
  dateText: { color: '#666', marginTop: 4 },

  filterContainer: { flexDirection: 'row', marginVertical: 16 },
  filterButton: { paddingVertical: 6, paddingHorizontal: 10, borderRadius: 14, marginRight: 8, backgroundColor: '#f0f0f0' },
  activeFilter: { backgroundColor: '#222' },
  filterText: { color: '#333' },
  activeFilterText: { color: '#fff' },

  addTaskContainer: {
    flexDirection: 'column',
    marginTop: 16,
    marginBottom: 28,
  },
  addTaskButton: {
    height: 44,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#222',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  plusIcon: { fontSize: 22 },
  addTaskIcon: { color: '#fff', fontSize: 15 },
  addTaskInput: {
    borderRadius: 8,
    borderWidth: 1,
    height: 50,
    borderColor: '#e0e0e0',
    paddingHorizontal: 15,
    paddingVertical: 10,
  },

  todoInput: { height: 44, borderRadius: 8, borderWidth: 1, borderColor: '#e0e0e0', paddingHorizontal: 10 },

  taskList: { flex: 1, paddingBottom: 24 },

  taskCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    padding: 16,
    borderRadius: 12,
    backgroundColor: 'white',
    borderColor: '#e0e0e0',
    marginBottom: 16,
  },
  
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  
  searchInput: {
    flex: 1,
    height: 40,
    borderRadius: 8,
    borderWidth: 0,
    paddingHorizontal: 0,
  },

  searchTodoInput: {
    borderColor: 'black',
    marginTop: 16,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1.4,
    borderRadius: 6,
    height: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },

  // taskCard: { flexDirection: 'row', alignItems: 'center', padding: 12, borderRadius: 8, backgroundColor: '#fafafa',shadowColor: '#000', shadowOffset: { width: 4, height: 2 },    elevation: 1,   shadowOpacity: 0.25, borderRadius: 10, marginBottom: 10 },
checkbox: {
  width: 30,
  height: 30,
  borderRadius: 15,
  borderWidth: 1,
  borderColor: '#D1D5DB', // soft gray
  justifyContent: 'center',
  alignItems: 'center',
  marginRight: 12,
  backgroundColor: '#fff',
},

checkedBox: {
  borderColor: '#10B981', // modern green
  backgroundColor: '#ECFDF5', // soft mint green background
},

checkmark: {
  color: '#059669', // darker green for good contrast
  fontWeight: '900',
  fontSize: 16,
  textAlign: 'center',
},

  taskContent: { flex: 1 },
  taskTitle: { fontSize: 16 },
  completedTask: { textDecorationLine: 'line-through', color: 'red' },
  taskDetails: { color: '#777', marginTop: 4 },

  taskActions: {  display:"flex", flexDirection: 'row' ,marginLeft: 8, gap: 5, justifyContent: 'center', alignItems: 'center' },
  starIcon: { fontSize: 18 },

  fab: { position: 'absolute', right: 18, bottom: 22, width: 56, height: 56, borderRadius: 28, backgroundColor: '#222', justifyContent: 'center', alignItems: 'center', zIndex: 10 },
  fabIcon: { color: '#fff', fontSize: 26 },

  FooterNavigationBar: {
    height: 60,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#292929',
    backgroundColor: 'black',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  navButton: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderTopWidth: 2,
    borderTopColor: 'transparent',
  },
  activeNavButton: { borderTopWidth: 2, borderTopColor: '#fff' },
  navText: { color: 'white', fontWeight: '500' },
  activeNavText: { color: 'white', fontWeight: '700' },

  headerTitle: { fontSize: 18, fontWeight: '600' },
  moreButton: { padding: 8 },
  moreIcon: { fontSize: 20 },

  backButton: { padding: 8 },
  backIcon: { fontSize: 18 },

  // Progress Page 
  progressScreen: { flex: 1, backgroundColor: '#F8FAFF' },
  progressScrollContent: { paddingTop: 30, paddingHorizontal: 20, paddingBottom: 44 },
  progressHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 },
  progressIconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#4338CA',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 8,
  },
  progressIconPlaceholder: { width: 44, height: 44 },
  progressTitle: { fontSize: 30, fontWeight: '700', color: '#0F172A' },
  progressSubtitle: { marginTop: 6, color: '#4B5563', fontSize: 15 },

  progressSummaryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 26,
    paddingHorizontal: 24,
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    marginBottom: 26,
    shadowColor: '#312E81',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 10,
    overflow: 'hidden',
    position: 'relative',
  },
  summaryAura: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: '#EEF2FF',
    opacity: 0.8,
    top: -110,
    right: -50,
  },
  summaryTextGroup: { flex: 1, marginRight: 18 },
  summaryLabel: {
    color: '#6366F1',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontSize: 12,
  },
  summaryValue: { fontSize: 44, fontWeight: '700', color: '#111827', marginTop: 8 },
  summaryMessage: { marginTop: 12, color: '#1D2939', lineHeight: 22, fontSize: 15 },
  summaryBadgeRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 16 },
  summaryBadge: {
    backgroundColor: '#EEF2FF',
    color: '#4F46E5',
    paddingVertical: 4,
    paddingHorizontal: 14,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: '600',
    marginRight: 8,
    marginBottom: 8,
  },
  progressGaugeWrapper: {
    width: 152,
    height: 152,
    borderRadius: 76,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#4338CA',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 10,
  },

  snapshotRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24 },
  snapshotChip: {
    flex: 1,
    marginRight: 12,
    backgroundColor: '#F1F5FF',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'flex-start',
    shadowColor: '#3730A3',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 5,
  },
  snapshotChipLast: { marginRight: 0 },
  snapshotChipAccent: { backgroundColor: '#F7ECFF' },
  snapshotChipWarning: { backgroundColor: '#FEF4EC' },
  snapshotIconWrapper: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E0E7FF',
    marginBottom: 10,
  },
  snapshotIconWrapperAccent: { backgroundColor: '#F3E8FF' },
  snapshotIconWrapperWarning: { backgroundColor: '#FFE8D7' },
  snapshotValue: { fontSize: 20, fontWeight: '700', color: '#111827' },
  snapshotLabel: { marginTop: 4, color: '#475467', fontSize: 12, fontWeight: '500' },

  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: 28 },
  metricCard: {
    flexBasis: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 18,
    marginBottom: 20,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 4,
  },
  metricCardFull: { flexBasis: '100%' },
  metricCardSuccess: { backgroundColor: '#ECFDF3' },
  metricCardNeutral: { backgroundColor: '#EFF6FF' },
  metricCardAccent: { backgroundColor: '#FEF3F2' },
  metricIcon: { width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center', marginBottom: 14 },
  metricIconSuccess: { backgroundColor: '#DCFCE7' },
  metricIconNeutral: { backgroundColor: '#DBEAFE' },
  metricIconAccent: { backgroundColor: '#FEE2E2' },
  metricValue: { fontSize: 30, fontWeight: '700', color: '#101828' },
  metricLabel: { marginTop: 4, color: '#475467', fontWeight: '500' },
  metricTextGroup: { flex: 1 },
  metricHelperText: { marginTop: 10, color: '#7F1D1D', fontSize: 13, lineHeight: 19 },

  progressSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 24,
    paddingHorizontal: 22,
    marginBottom: 28,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  sectionTitle: { fontSize: 20, fontWeight: '700', color: '#0F172A' },
  sectionSubtitle: { marginTop: 8, color: '#475467', lineHeight: 21 },
  highlightItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderColor: '#E4E7EC',
  },
  highlightItemFirst: { paddingTop: 4 },
  highlightItemLast: { borderBottomWidth: 0, paddingBottom: 0, marginBottom: -6 },
  highlightIcon: { width: 38, height: 38, borderRadius: 19, justifyContent: 'center', alignItems: 'center', marginRight: 14 },
  highlightIconUpcoming: { backgroundColor: '#DBEAFE' },
  highlightIconOverdue: { backgroundColor: '#FEE2E2' },
  highlightTextGroup: { flex: 1 },
  highlightTitle: { fontWeight: '600', color: '#101828' },
  highlightMeta: { marginTop: 2, color: '#475467' },
  highlightMetaOverdue: { color: '#B91C1C' },
  highlightPill: { backgroundColor: '#FFEDD5', color: '#C2410C', paddingVertical: 4, paddingHorizontal: 10, borderRadius: 12, fontWeight: '600', fontSize: 12 },
  emptyStateText: { marginTop: 16, color: '#475467' },

  tipCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#F5F5FF',
    borderRadius: 18,
    padding: 18,
    marginTop: 16,
    shadowColor: '#3730A3',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 4,
  },
  tipIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    shadowColor: '#4338CA',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  tipIconWrapperEnergy: { backgroundColor: '#FFF7ED' },
  tipIconWrapperCalm: { backgroundColor: '#EEF2FF' },
  tipContent: { marginLeft: 16, flex: 1 },
  tipTitle: { fontWeight: '600', color: '#1F2937', fontSize: 15 },
  tipDescription: { marginTop: 8, color: '#475467', lineHeight: 20, fontSize: 13 },

  priorityTaskText:{borderStyle:'solid', borderColor:'black', justifyContent:'center', textAlign:'center', color:'white', borderRadius: 10, padding: 3 , borderWidth:1, width:70, marginTop:12}

});


// backgroundColor:"red"
